[package]
name = "brush-cli"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
indicatif.workspace = true
clap.workspace = true
brush-process.path = "../brush-process"
brush-train.path = "../brush-train"

[lints]
workspace = true
